#!/bin/bash -eu

# Install Homebrew
install_homebrew() {
  # if 文で brew があったら走らない
  if type brew >/dev/null 2>&1; then
    echo "Homebrew は既にインストール済みです"
  else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

# Main
install_homebrew
