#!/bin/bash -eu

# Install Homebrew
uninstall_homebrew() {
  # if 文で brew があったら走らない
  if type brew >/dev/null 2>&1; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
  else
    echo "brew のコマンドの存在が存在しません."
    echo "処理を終了します."
  fi
}

# Main
uninstall_homebrew
