#!/bin/bash -eu

# Install package
install_package() {
  npm install --global trash-cli
  npm install --global browserify
  npm install --global express-generator
  npm install --global generator-hubot
  npm install --global gulp-cli
  npm install --global hubot
  npm install --global uglify-js
  npm install --global typescript
  npm install --global yo
}

# Main
install_package
